package org.cytoscape.gnc.view.configurationDialogs;

import java.io.File;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import org.cytoscape.gnc.controller.tasks.ExecuteGNCTask;
import org.cytoscape.gnc.controller.utils.CySwing;
import org.cytoscape.gnc.model.businessobjects.DBFile;
import org.cytoscape.work.Task;
import org.cytoscape.work.TaskManager;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class ConfigurationDialog extends javax.swing.JDialog {
    private final TaskManager taskManager;
    private final Map<String, DBFile> preloadedDatabases = new LinkedHashMap<String, DBFile>();
    private final Map<String, DBFile> customDatabases = new LinkedHashMap<String, DBFile>();
    private final DefaultListModel<String> databaseListModel;
    private final CSVDelimiterSelector csvDelimiterSelector = new  CSVDelimiterSelector();
    private File currentFolder;
    
    /**
     * Creates new form NewJDialog
     */
    public ConfigurationDialog(TaskManager taskManager) {
        super(CySwing.getDesktopJFrame(), true);
        preloadedDatabases.put("BioGRID (Human)", new DBFile("/databases/BioGrid-Human.txt", ',', true));
        preloadedDatabases.put("BioGRID (Yeast)", new DBFile("/databases/BioGrid-Yeast.txt", ',', true));
        preloadedDatabases.put("Scharomyces Genome Database (SGD)", new DBFile("/databases/SGD.txt", ',', true));
        preloadedDatabases.put("YeastNet (V3)", new DBFile("/databases/YeastNetV3.txt", ',', true));
        
        databaseListModel = new DefaultListModel();
        for (String database : preloadedDatabases.keySet()) {
            databaseListModel.addElement(database);
        }
        
        initComponents();
        setLocationRelativeTo(CySwing.getDesktopJFrame());
        this.taskManager = taskManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        databasePanel = new javax.swing.JLayeredPane();
        loadCustomDatabaseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseList = new javax.swing.JList();
        runGNCButton = new javax.swing.JButton();
        explanationLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        setTitle("GNC");
        setResizable(false);

        databasePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Database"));

        loadCustomDatabaseButton.setText("Load custom database");
        loadCustomDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCustomDatabaseButtonActionPerformed(evt);
            }
        });

        databaseList.setModel(databaseListModel);
        jScrollPane1.setViewportView(databaseList);

        javax.swing.GroupLayout databasePanelLayout = new javax.swing.GroupLayout(databasePanel);
        databasePanel.setLayout(databasePanelLayout);
        databasePanelLayout.setHorizontalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadCustomDatabaseButton)
                .addGap(98, 98, 98))
        );
        databasePanelLayout.setVerticalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadCustomDatabaseButton)
                .addContainerGap())
        );
        databasePanel.setLayer(loadCustomDatabaseButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        databasePanel.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        runGNCButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        runGNCButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exec.gif"))); // NOI18N
        runGNCButton.setText("Run GNC");
        runGNCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runGNCButtonActionPerformed(evt);
            }
        });

        explanationLabel.setText("<html>Select a biological database to compare your network with using GNC. You can select one of our pre-loaded databases or load you own one in CSV format.</html>");
        explanationLabel.setPreferredSize(new java.awt.Dimension(958, 48));
        explanationLabel.setSize(new java.awt.Dimension(45, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databasePanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(runGNCButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(explanationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(explanationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(runGNCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        databasePanel.getAccessibleContext().setAccessibleName("Datbase");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runGNCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runGNCButtonActionPerformed
        String database = this.databaseList.getSelectedValue() != null
                ? this.databaseList.getSelectedValue().toString()
                : null;
        setVisible(false);

        DBFile dbFile = this.preloadedDatabases.get(database);
        if (dbFile == null) {
            dbFile = this.customDatabases.get(database);
        }
        if (database == null) {
            CySwing.displayPopUpMessage("No database selected.");
            return;
        }
        
        taskManager.execute(new org.cytoscape.work.TaskIterator(new Task[] { new ExecuteGNCTask(dbFile, this) }));
    }//GEN-LAST:event_runGNCButtonActionPerformed

    private void loadCustomDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCustomDatabaseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(currentFolder);
        fileChooser.setAccessory(csvDelimiterSelector);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == 0) {
            currentFolder = new File(fileChooser.getSelectedFile().getParent());
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            char csvDelimiter = csvDelimiterSelector.getDelimiter();
            DBFile  dbFile = new DBFile(filePath, csvDelimiter);
            if (!databaseListModel.contains(filePath)) {
                databaseListModel.addElement(filePath);
            }
            customDatabases.put(filePath, dbFile);
            databaseList.setSelectedValue(filePath, true);
        }
    }//GEN-LAST:event_loadCustomDatabaseButtonActionPerformed
    
    public void removeDB(DBFile dbFile) {
       customDatabases.remove(dbFile.getPath());
       databaseListModel.removeElement(dbFile.getPath());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList databaseList;
    private javax.swing.JLayeredPane databasePanel;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadCustomDatabaseButton;
    private javax.swing.JButton runGNCButton;
    // End of variables declaration//GEN-END:variables
}
