package org.cytoscape.gnc.view.configurationDialogs;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class CSVDelimiterSelector extends javax.swing.JPanel {
    private char csvDelimiter = ';';
    /**
     * Creates new form CSVSeparatorSelector
     */
    public CSVDelimiterSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csvDelimiterGroup = new javax.swing.ButtonGroup();
        fileSeparatorLabel = new javax.swing.JLabel();
        semicolonRadioButton = new javax.swing.JRadioButton();
        comaRadioButton = new javax.swing.JRadioButton();
        tabRadioButton = new javax.swing.JRadioButton();
        spaceRadioButton = new javax.swing.JRadioButton();

        csvDelimiterGroup.add(tabRadioButton);
        csvDelimiterGroup.add(comaRadioButton);
        csvDelimiterGroup.add(semicolonRadioButton);
        csvDelimiterGroup.add(spaceRadioButton);

        fileSeparatorLabel.setText("CSV delimiter");

        semicolonRadioButton.setSelected(true);
        semicolonRadioButton.setText("Semicolon");
        semicolonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semicolonRadioButtonActionPerformed(evt);
            }
        });

        comaRadioButton.setText("Coma");
        comaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaRadioButtonActionPerformed(evt);
            }
        });

        tabRadioButton.setText("Tab");
        tabRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabRadioButtonActionPerformed(evt);
            }
        });

        spaceRadioButton.setText("Space");
        spaceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semicolonRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileSeparatorLabel)
                            .addComponent(tabRadioButton)
                            .addComponent(comaRadioButton)
                            .addComponent(spaceRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileSeparatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semicolonRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void semicolonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semicolonRadioButtonActionPerformed
        csvDelimiter = ';';
    }//GEN-LAST:event_semicolonRadioButtonActionPerformed

    private void comaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaRadioButtonActionPerformed
        csvDelimiter = ',';
    }//GEN-LAST:event_comaRadioButtonActionPerformed

    private void tabRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabRadioButtonActionPerformed
        csvDelimiter = '\t';
    }//GEN-LAST:event_tabRadioButtonActionPerformed

    private void spaceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceRadioButtonActionPerformed
        csvDelimiter = ' ';
    }//GEN-LAST:event_spaceRadioButtonActionPerformed

    public char getDelimiter() {
        return csvDelimiter;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton comaRadioButton;
    private javax.swing.ButtonGroup csvDelimiterGroup;
    private javax.swing.JLabel fileSeparatorLabel;
    private javax.swing.JRadioButton semicolonRadioButton;
    private javax.swing.JRadioButton spaceRadioButton;
    private javax.swing.JRadioButton tabRadioButton;
    // End of variables declaration//GEN-END:variables
}
